- name: Check behat env.
  stat:
    path: "{{ app_directory }}/.env.behat"
  register: run_behat

- name: Check behat features.
  stat:
    path: "{{ app_directory }}/features/pipeline"
  register: behat_features

- name: Run behat tests.
  block:
    - name: Copy behat env file.
      copy:
        src: "{{ app_directory }}/.env.behat"
        dest: "{{ app_directory }}/.env"

    - name: Run Behat tests.
      shell: 'vendor/bin/behat features/pipeline'
      args:
        chdir: "{{ app_directory }}"

    - name: Remove behat env.
      file:
        path: "{{ app_directory }}/.env"
        state: absent
  when: run_behat.stat.exists and behat_features.stat.exists
